### ISSUE TITLE
Shiny assessment feedback

### ISSUE THREAD

**Issue by jonekeat** [wilson-pang/R_Shiny_Assessment#16]
Hi @wilson-pang , thanks for attempting the shiny assessment, please find my feedbacks below:

1. The interface fully fulfilled all requirements, user is able to input some data, calculate and visualize result all in the app, well done!

2. For tail factor, since this value normal ranges from 1 to 2, consider putting the `step` as 0.1, so user can increment the value in smaller step
https://github.com/wilson-pang/R_Shiny_Assessment/blob/fcf0f932fd941267d22fb3301b762176cf153566/app1/app.R#L17

3. For UI, I noticed there is a large blank space below the instruction, we should remove this space. And for download button, this is a good addition, but should consider put in a more appropriate place, so user easier to locate the button, eg top right corner of the UI.
![image](https://github.com/user-attachments/assets/e58e1b83-dabd-4f7b-bbd2-723dec83a8f1)

4. For table & graph, we can put the number formatting to currency, eg add thousand separator and put 2 decimal places
![image](https://github.com/user-attachments/assets/a9443786-0914-485a-aac8-7b14bdf3ad41)

5. For graph, the legend seem to have some labels covered, we can remove label if any
![image](https://github.com/user-attachments/assets/5659a3b4-d18f-4a93-84a5-db5497e5e2a9)

6. We can enhance the table cell formatting by putting different cell/background color to differentiate which cell is input values and which is projected

7. The code is easy to read and neat, but we can avoid loading the `rsconnect` library since this library only needed when we deploy, it is unnecessary for app running
https://github.com/wilson-pang/R_Shiny_Assessment/blob/fcf0f932fd941267d22fb3301b762176cf153566/app1/app.R#L5

**Comment by wilson-pang** [comment]
Thank you!
